name: github pages

on:
  push:
    branches:
      - 'feature/article-1'
    paths:
      - 'content/posts/**'
  pull_request:

permissions:
  contents: write

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: blogpub
        uses: protiumx/blogpub@main
        with:
          articles_folder: content/posts
          devto_api_key: occqkrPQgV1JxoYkqrvT85yR
          gh_token: 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
          medium_token: 2f23ed02d4e779247bc65e17bf2b29eecb73f2ff60d69ad95bec786aae626c3f0
          medium_user_id: 9d9b38cc4743
