name: github pages

on:
  push:
    branches:
      - 'feature/article-1'
    paths:
      - 'content/posts/**'
  pull_request:

permissions:
  contents: write

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: blogpub
        uses: protiumx/blogpub@main
        with:
          articles_folder: content/posts
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          gh_token: ${{ secrets.TOKEN }}
          medium_token: ${{ secrets.MEDIUM_TOKEN }}
          medium_user_id: 9d9b38cc4743
