name: 'publish'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/posts/**'

concurrency:
  cancel-in-progress: true
  group: publish-${{ github.head_ref || github.ref }}

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: blogpub
        uses: protiumx/blogpub@v0.6.0
        with:
          devto_api_key: occqkrPQgV1JxoYkqrvT85yR
          gh_token: ${{ secrets.GH_TOKEN }}
          medium_token: 2695028acdb67957cdfec5853a6f1b6aae888850a0104e150d115c7414901e06e
          medium_user_id: 9d9b38cc4743

#jobs:
#  publish:
#    name: publish new article
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: blogpub
#        uses: protiumx/blogpub@main
#        with:
#          articles_folder: content/posts
#          devto_api_key: occqkrPQgV1JxoYkqrvT85yR
#          gh_token: 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
#          medium_token: 2695028acdb67957cdfec5853a6f1b6aae888850a0104e150d115c7414901e06e
#          medium_user_id: 9d9b38cc4743

